# Use the b2bi-customization base image
FROM cp.icr.io/cp/ibm-b2bi/b2bi-customization:6.2.1.0

USER root

# copy files
COPY --chown=1010:0 ./liberty/  /ibm/b2bi/customization/liberty/
COPY --chown=1010:0 ./startup/ /ibm/b2bi/customization/startup/
COPY --chown=1010:0 ./thirdparty/ /ibm/b2bi/customization/thirdparty/
COPY --chown=1010:0 ./services/ /ibm/b2bi/customization/services/
COPY --chown=1010:0 ./userexits/ /ibm/b2bi/customization/userexits/
COPY --chown=1010:0 ./protocols/ /ibm/b2bi/customization/protocols/
COPY --chown=1010:0 ./uibranding/ /ibm/b2bi/customization/uibranding/
COPY --chown=1010:0 ./properties/ /ibm/b2bi/customization/properties/
    

USER 1010
ENTRYPOINT ["./b2biCustomizationContainerStart.sh"]