# Use the UBI9 minimal image as the base
FROM registry.access.redhat.com/ubi9/ubi-minimal

# Set environment variables
ENV RESOURCES_SRC_DIR=/resources \
    RESOURCES_DIR_MOUNT=/var/nfs-data/resources \
    DB_VENDOR=DB2

# Create a group and user with UID 1011 and Create necessary directories
RUN groupadd -g 1011 pemgroup && \
    useradd -m -u 1011 -d $RESOURCES_SRC_DIR -g pemgroup -s /sbin/nologin -c "PEM custom user" pemuser && \
    mkdir -p $RESOURCES_DIR_MOUNT/dbdrivers $RESOURCES_DIR_MOUNT/pcm && \
    chmod 777 $RESOURCES_DIR_MOUNT

# Define a volume for persistent storage
VOLUME $RESOURCES_DIR_MOUNT

# Copy files from the local directory to the container's resources directory
COPY ./files $RESOURCES_SRC_DIR/

# Ensure ResourcesCopy.sh is executable after copying
RUN chmod 755 $RESOURCES_SRC_DIR/ResourcesCopy.sh

# Switch to the custom user
USER pemuser

# Set the working directory
WORKDIR $RESOURCES_SRC_DIR

# # Set the entry point to run the script
ENTRYPOINT ["./ResourcesCopy.sh"]
